# Generated by Django 5.1.1 on 2024-10-10 00:17

import attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clock",
            name="clock_unique",
        ),
        migrations.AddField(
            model_name="clock",
            name="date_stamp",
            field=models.DateTimeField(default="2024-10-10", verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="clock",
            name="break_time",
            field=models.IntegerField(default=1, verbose_name="Break time"),
        ),
        migrations.AlterField(
            model_name="clock",
            name="clock",
            field=models.CharField(
                choices=[("clock_in", "In"), ("clock_out", "Out")],
                default="In",
                max_length=20,
                verbose_name="In/Out",
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="location",
            field=models.CharField(
                choices=[("office", "Office"), ("telework", "Telework")],
                default="Office",
                max_length=20,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="time_stamp",
            field=models.DateTimeField(default="09:17:16", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="clock",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Username",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Department"),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=attendance.models.create_id,
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
                verbose_name="User ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="clock",
            constraint=models.UniqueConstraint(
                fields=("user", "date_stamp", "clock"), name="clock_unique"
            ),
        ),
    ]
