# Generated by Django 5.1.1 on 2024-10-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_remove_clock_clock_unique_clock_date_stamp_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clock",
            name="clock_unique",
        ),
        migrations.AlterUniqueTogether(
            name="clock",
            unique_together={("user", "time_stamp", "clock")},
        ),
        migrations.AlterField(
            model_name="clock",
            name="time_stamp",
            field=models.DateTimeField(
                default="2024-10-10 09:46:32", verbose_name="Datetime"
            ),
        ),
        migrations.RemoveField(
            model_name="clock",
            name="date_stamp",
        ),
    ]
